hotel/urls.py
from django.urls import path, include
from .views import (
    home_view,
    hotel_detail_view,
    make_reservation,
    reservations_view
)

urlpatterns = [
    path('', home_view, name="home"),
    path('<slug:slug>', hotel_detail_view, name="hotel.details"),
    path('reservation/<slug:slug>', make_reservation, name="hotel.reservation.create"),
    path('hotel/reservations', reservations_view, name="hotel.reservation"),
    path('admin/', include('hotel.admin_urls'))
]

traveler/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('hotel.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hotel/models.py
from django.db import models

hotel/models/Hotel.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.utils.text import slugify
import string
import random
from django.urls import reverse
from os.path import splitext
from hashlib import sha224
from datetime import datetime


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


def get_random_string(length):
    # choose from all lowercase letter
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str.encode('UTF-8')


def upload_to_id_image(instance, filename):
    extension = splitext(filename)[1].lower()
    return 'hotels/%(year)s/%(month)s/%(day)s/%(name)s%(extension)s' % {
        'year': datetime.now().strftime("%Y"),
        'month': datetime.now().strftime("%m"),
        'day': datetime.now().strftime("%d"),
        'name': sha224(get_random_string(10)).hexdigest(),
        'extension': extension,
    }


# Create your models here.
class Hotel(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    feature_image = ProcessedImageField(upload_to=upload_to_id_image,
                                        format='JPEG',
                                        processors=[ResizeToFill(500, 500)],
                                        options={
                                            'quality': 90
                                        })
    latitude = models.CharField(max_length=20)
    longitude = models.CharField(max_length=20)
    address = models.TextField()
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    total_rating = models.FloatField(default=0.0)
    total_emotion_rating = models.FloatField(default=0.0)
    price = models.IntegerField(default=0)
    city = models.CharField(max_length=255, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name + "-" + rand_slug())
        super(Hotel, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('hotel.details', kwargs={'slug': self.slug})

hotel/models/HotelImage.py
from django.db import models
from .Hotel import Hotel
import string
import random
from hashlib import sha224
from datetime import datetime
from os.path import splitext
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


def get_random_string(length):
    # choose from all lowercase letter
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str.encode('UTF-8')


def upload_to_id_image(instance, filename):
    extension = splitext(filename)[1].lower()
    return 'hotels/%(year)s/%(month)s/%(day)s/%(name)s%(extension)s' % {
        'year': datetime.now().strftime("%Y"),
        'month': datetime.now().strftime("%m"),
        'day': datetime.now().strftime("%d"),
        'name': sha224(get_random_string(10)).hexdigest(),
        'extension': extension,
    }


class HotelImage(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, null=True)
    image = ProcessedImageField(upload_to=upload_to_id_image,
                                format='JPEG',
                                processors=[ResizeToFill(500, 500)],
                                options={
                                    'quality': 90
                                })

hotel/models/HotelReviews.py
from django.db import models
from authentication.models import User
from hotel.models.Hotel import Hotel


class HotelReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    location = models.FloatField(default=0.0)
    value_of_money = models.FloatField(default=0.0)
    cleanliness = models.FloatField(default=0.0)
    services = models.FloatField(default=0.0)
    avg_rating = models.FloatField(default=0.0)
    comment = models.TextField()
    emoji = models.CharField(max_length=20, default='neutral.png')
    emotion = models.CharField(max_length=20, default='Neutral')
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    modified_at = models.DateTimeField(auto_now_add=True, blank=True)

hotel/models/Reservation.py
from django.db import models
from authentication.models import User
from hotel.models.Hotel import Hotel


class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    total_price = models.IntegerField()

hotel/forms/CreateHotelForm.py
from django import forms
from django.core.files.images import get_image_dimensions
from hotel.models.Hotel import Hotel


class CreateHotelForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "name",
                "placeholder": "Hotel's name"
            }
        ),
        required=True
    )

    feature_image = forms.ImageField(required=True)

    latitude = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "latitude",
                "placeholder": "Latitude",
                'readonly': True
            }
        ),
        required=True
    )

    longitude = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "longitude",
                "placeholder": "Longitude",
                'readonly': True
            }
        ),
        required=True
    )

    address = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "address",
                "placeholder": "Address"
            }
        ),
        required=True
    )

    city = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "address",
                "placeholder": "City"
            }
        ),
        required=True
    )

    price = forms.CharField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control",
                "id": "address",
                "placeholder": "Price"
            }
        ),
        required=True
    )

    description = forms.Textarea(
        attrs={
            "class": "form-control",
            "id": "description",
            "required": "true"
        }
    )

    is_active = forms.BooleanField(initial=True)

    class Meta:
        model = Hotel
        fields = (
            'name',
            'feature_image',
            'latitude',
            'longitude',
            'address',
            'description',
            'is_active',
            'price',
            'city'
        )
        widgets = {
            'description': forms.Textarea(attrs={
                "class": "form-control",
                "id": "description",
                "required": "true"
            })
        }

    def clean(self, *args, **kwargs):
        name = self.cleaned_data.get('name')
        feature_image = self.cleaned_data.get('feature_image')
        latitude = self.cleaned_data.get('latitude')
        longitude = self.cleaned_data.get('longitude')
        address = self.cleaned_data.get('address')
        description = self.cleaned_data.get('description')
        is_active = self.cleaned_data.get('is_active')
        price = self.cleaned_data.get('price')
        city = self.cleaned_data.get('price')

        if not feature_image:
            self.add_error('feature_image', "Please provide a feature image.")
            raise forms.ValidationError("Please provide a feature image.")
        else:
            w, h = get_image_dimensions(feature_image)
            if w < 500:
                self.add_error('feature_image', "Width or height of the image should be greater then 500px.")
                raise forms.ValidationError("Width or height of the image should be greater then 500px.")
            if h < 500:
                self.add_error('feature_image', "Width or height of the image should be greater then 500px.")
                raise forms.ValidationError("Width or height of the image should be greater then 500px.")

        return super(CreateHotelForm, self).clean(*args, **kwargs)

hotel/forms/CreateReviewForm.py
from django import forms


class CreateReviewForm(forms.Form):
    location = forms.CharField(widget=forms.HiddenInput())
    value_of_money = forms.CharField(widget=forms.HiddenInput())
    cleanliness = forms.CharField(widget=forms.HiddenInput())
    services = forms.CharField(widget=forms.HiddenInput())
    comment = forms.CharField(
        widget=forms.Textarea(
                attrs={
                    "class": "form-control",
                    "id": "comment",
                    "required": "true"
                }
            )
    )

    def clean(self, *args, **kwargs):
        location = self.cleaned_data.get('location')
        value_of_money = self.cleaned_data.get('value_of_money')
        cleanliness = self.cleaned_data.get('cleanliness')
        services = self.cleaned_data.get('services')
        comment = self.cleaned_data.get('comment')

        if not location:
            self.add_error('rating', 'Please provide the location rating.')
            raise forms.ValidationError('Please provide the location rating.')

        if not value_of_money:
            self.add_error('value_of_money', 'Please provide the value of money rating.')
            raise forms.ValidationError('Please provide the value of many rating.')

        if not cleanliness:
            self.add_error('cleanliness', 'Please provide the cleanliness rating.')
            raise forms.ValidationError('Please provide the cleanliness rating.')

        if not services:
            self.add_error('services', 'Please provide the services rating.')
            raise forms.ValidationError('Please provide the services rating.')

        if not comment:
            self.add_error('comment', 'Please provide the comment.')
            raise forms.ValidationError('Please provide the comment.')

        return super(CreateReviewForm, self).clean(*args, **kwargs)

hotel/views.py
from django.shortcuts import render, get_object_or_404
from hotel.models.Hotel import Hotel
from hotel.models.HotelReviews import HotelReview
from hotel.forms.CreateReviewForm import CreateReviewForm
from textblob import TextBlob
from django.db.models import Sum
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from hotel.models.Reservation import Reservation
from hotel.models.HotelImage import HotelImage


# Create your views here.


def home_view(request):
    cities = Hotel.objects.order_by().values('city').distinct()
    hotels = Hotel.objects.filter(is_active=True)
    if request.GET.get('q'):
        hotels = hotels.filter(name__icontains=request.GET.get('q'))
    else:
        if request.GET.get('price'):
            hotels = hotels.filter(price__lte=request.GET.get('price'))
        if request.GET.get('rating'):
            hotels = hotels.filter(total_rating__lte=request.GET.get('rating'))
        if request.GET.get('city'):
            hotels = hotels.filter(city__exact=request.GET.get('city'))
    hotels = hotels.all().order_by('-total_emotion_rating')
    context = {
        'hotels': hotels,
        'cities': cities
    }
    return render(request, 'hotel/home.html', context)


def hotel_detail_view(request, slug):
    hotel = get_object_or_404(Hotel, slug=slug)
    gallery = HotelImage.objects.filter(hotel=hotel).all()
    gallery_count = range(gallery.count() + 1)
    reviews = HotelReview.objects.filter(hotel=hotel).all().order_by('-id')
    total_location = HotelReview.objects.filter(hotel=hotel).aggregate(Sum('location'))['location__sum']
    print(total_location)
    total_value_of_money = HotelReview.objects.filter(hotel=hotel).aggregate(Sum('value_of_money'))['value_of_money__sum']
    total_cleanliness = HotelReview.objects.filter(hotel=hotel).aggregate(Sum('cleanliness'))['cleanliness__sum']
    total_services = HotelReview.objects.filter(hotel=hotel).aggregate(Sum('services'))['services__sum']
    print(total_location)
    form = CreateReviewForm(request.POST or None)
    if form.is_valid():
        HotelReview.objects.filter()
        location = form.cleaned_data.get('location')
        value_of_money = form.cleaned_data.get('value_of_money')
        cleanliness = form.cleaned_data.get('cleanliness')
        services = form.cleaned_data.get('services')
        avg_rating = (float(location) + float(value_of_money) + float(services) + float(cleanliness)) / 4.0
        comment = form.cleaned_data.get('comment')
        image, sentiment, polarity = text_analyzer(comment)
        hotel.total_emotion_rating = hotel.total_emotion_rating + float("{:.2f}".format(polarity))
        HotelReview.objects.create(location=location, value_of_money=value_of_money, cleanliness=cleanliness,
                                   services=services, avg_rating=avg_rating, comment=comment, user=request.user,
                                   hotel=hotel, emoji=image, emotion=sentiment)
        total_sum_rating = HotelReview.objects.filter(hotel=hotel).aggregate(Sum('avg_rating'))
        total_rating_count = HotelReview.objects.filter(hotel=hotel).count()
        hotel.total_rating = total_sum_rating['avg_rating__sum'] / total_rating_count
        hotel.save()
        messages.add_message(request, messages.SUCCESS, "Your review is submitted successfully.")

    context = {
        'hotel': hotel,
        'form': form,
        'reviews': reviews,
        'total_location': total_location,
        'total_value_of_money': total_value_of_money,
        'total_cleanliness': total_cleanliness,
        'total_services': total_services,
        'gallery': gallery,
        'gallery_count': gallery_count
    }
    return render(request, 'hotel/hotel_details.html', context)


def text_analyzer(text):
    text_blob = TextBlob(text)
    return get_analysis(text_blob.sentiment)


def get_analysis(sentiment):
    if sentiment.polarity > 0.4:
        if 0.4 >= sentiment.polarity <= 0.6:
            return "neutral.png", "Neutral", sentiment.polarity
        if 0.6 >= sentiment.polarity <= 0.8:
            return "satisfied.png", "Happy", sentiment.polarity
        if sentiment.polarity > 0.8:
            return "smile.png", "Very Happy", sentiment.polarity
    else:
        return "sad.png", "Very Angry", sentiment.polarity


@login_required
def make_reservation(request, slug):
    hotel = get_object_or_404(Hotel, slug=slug)
    if request.method == 'POST':
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        total_price = request.POST.get('total_price')
        Reservation.objects.create(start_date=start_date, end_date=end_date, total_price=total_price, hotel=hotel, user=request.user)
        messages.add_message(request, messages.SUCCESS, "Your hotel reservation is complete successfully.")
    context = {
        'hotel': hotel
    }
    return render(request, 'hotel/create_reservation.html', context)


@login_required
def reservations_view(request):
    if request.user.role == 'admin':
        reservations = Reservation.objects.all().order_by('-id')
    else:
        reservations = Reservation.objects.filter(user=request.user).all().order_by('-id')
    paginator = Paginator(reservations, per_page=10)
    page_number = request.GET.get('page')
    reservations = paginator.get_page(page_number)
    context = {
        'reservations': reservations
    }
    return render(request, 'hotel/reservations.html', context)

templates/hotel/create_reservation.html
{% extends 'layouts/app.html' %}

{% block title %} Hotel Reservation - {{ hotel.name }} {% endblock %}

{% block content %}
    <!-- Title -->
    <div class="row heading-bg">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h5 class="txt-dark">Reservation</h5>
        </div>
        <!-- Breadcrumb -->
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active"><a href="#"><span>{{ hotel.name|upper }}</span></a></li>
            </ol>
        </div>
        <!-- /Breadcrumb -->
    </div>
    <!-- /Title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default card-view">
                <div class="panel-wrapper collapse in">
                    <div class="panel-heading">Make Your Reservation</div>
                    <div class="panel-body">
                        {% include 'includes/messages.html' %}
                        <form action="{% url 'hotel.reservation.create' hotel.slug %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="dates" class="control-label mb-10">Staying Date</label>
                                    <input type="text" class="form-control" id="reservation_dates" required>
                                    <input type="hidden" name="start_date" id="start_date" value="{% now 'Y-m-d' %}">
                                    <input type="hidden" name="end_date" id="end_date" value="{% now 'Y-m-d' %}">
                                    <input type="hidden" name="total_price" id="total_price" value="{{ hotel.price }}">
                                </div>
                            </div>
                            <div class="row" style="margin-top: 20px; margin-bottom: 20px">
                                <div class="col-md-12">
                                    <h3>
                                        Rs<span id="price">{{ hotel.price }} / Day</span>
                                    </h3>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-info">Book your room now</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>

        function days(date_1, date_2){
            let difference = date_1.getTime() - date_2.getTime();
            return Math.ceil(difference / (1000 * 3600 * 24));
        }

        $("#reservation_dates").daterangepicker({
            minDate: new Date()
        }, function(start, end, label){
            $("#start_date").val(start.format('YYYY-MM-DD'));
            $("#end_date").val(end.format('YYYY-MM-DD'));
            var total_price = parseInt('{{ hotel.price }}') * days(new Date(end), new Date(start))
            $("#total_price").val(total_price);
            $("#price").html(total_price);
        });
    </script>
{% endblock %}

templates/hotel/home.html
{% extends 'layouts/app.html' %}

{% block title %} Home - traveler {% endblock %}
{% load custom_tags %}

{% block content %}
    <!-- Title -->
    <div class="row heading-bg">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h5 class="txt-dark">Home</h5>
        </div>
        <!-- Breadcrumb -->
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active"><a href="#"><span>Hotels</span></a></li>
            </ol>
        </div>
        <!-- /Breadcrumb -->
    </div>
    <!-- /Title -->

    {% include 'includes/search_form.html' with cities=cities %}

    <div class="row">
        {% for hotel in hotels %}
        <div class="col-md-3">
            <div class="panel panel-default card-view pa-0">
                <div class="panel-wrapper collapse in">
                    <div class="panel-body pa-0">
                        <article class="col-item">
                            <div class="photo">
                                <a href="{% url 'hotel.details' hotel.slug %}">
                                    <img src="{{ hotel.feature_image.url }}"
                                         class="img-responsive" alt="{{ hotel.name|slice:':30' }}">
                                </a>
                            </div>
                            <div class="info">
                                <h6>{{ hotel.name|upper }}</h6>
                                <div class="product-rating">
                                    <div style="display: flex; justify-content: space-between; align-items: center">
                                        <div class="my-rating-fixed" data-rating="{{ hotel.total_rating|floatformat:1 }}"></div>
                                        <strong class="text-info">
                                            {% if hotel.hotelreview_set.count > 0 %}
                                                {{ hotel.total_rating|floatformat:1 }} ({{ hotel.total_rating|rating }})
                                            {% endif %}
                                        </strong>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/hotel/reservations.html
{% extends 'layouts/app.html' %}

{% block title %} Hotel Reservation - {{ hotel.name }} {% endblock %}

{% load humanize %}

{% block content %}
    <!-- Title -->
    <div class="row heading-bg">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h5 class="txt-dark">Reservations</h5>
        </div>
        <!-- Breadcrumb -->
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active"><a href="#"><span>Reservations</span></a></li>
            </ol>
        </div>
        <!-- /Breadcrumb -->
    </div>
    <!-- /Title -->


    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default border-panel card-view">
                <div class="panel-heading">
                    <div class="pull-left">Reservations</div>
                </div>
                <div class="panel-wrapper collapse in">
                    <div class="panel-body">
                        <div class="table-responsive ">
                            <table class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Hotel</th>
                                    {% if user.role == 'admin' %}
                                        <th>User</th>
                                    {% endif %}
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Price</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for reservation in reservations %}
                                        <tr>
                                            <td>{{ reservation.id }}</td>
                                            <td>
                                                {{ reservation.hotel.name }}
                                            </td>
                                            {% if user.role == 'admin' %}
                                                <td>{{ reservation.user.username }}</td>
                                            {% endif %}
                                            <td>{{ reservation.start_date }}</td>
                                            <td>{{ reservation.end_date }}</td>
                                            <td>Rs {{ reservation.total_price|intcomma }}/-</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% include 'includes/pagination.html' with pagination=reservations %}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}